version: 0.2

phases:
  build:
    commands:
      # install rust and cargo
      # -y option to accept default configuration
      - curl https://sh.rustup.rs -sSf | sh -s -- -y

      # configure shell so we can use "cargo" command
      - . "$HOME/.cargo/env"     

      # reference cargo directly
      - cargo --version

      # install homebrew
      - NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      # install cargo-lambda
      - /home/linuxbrew/.linuxbrew/bin/brew tap cargo-lambda/cargo-lambda
      - /home/linuxbrew/.linuxbrew/bin/brew install cargo-lambda

      # build the lambda
      - cd hem-lambda
      - cargo lambda build --arm64 -r --package=hem-lambda
      
  post_build:
    commands:
      - echo "Running post_build commands"