on: [ push ]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Installing Numpy
        run: |
          pip install pip --upgrade
          pip install numpy
      - name: Installing scipy
        run: pip install scipy
      - run: cargo test --workspace --exclude hem-lambda --exclude wrappers-lambda
      - run: cargo rustc --no-default-features -- -Awarnings
